[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fire>=0.7.1",
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "mypy>=2.3.0",
    "pydantic>=2.13.4",
    "uv>=0.12.1",
    "vllm>=0.26.0",
]

[tool.flake8]
extend-exclude = [
	".venv",
	"vllm*",
	"moulinette*"
]

[[tool.mypy.overrides]]
module = ["vllm", "vllm.*"]
ignore_errors = true

[tool.mypy]
exclude = "moulinette"
